version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - mern-app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    volumes:
      # Mount these directories for development
      - ./server/temp:/app/temp
      - ./server/outputs:/app/outputs
      # Don't overwrite node_modules with host directory
      - /app/node_modules
    restart: unless-stopped
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
