services:
  - type: web
    name: cavelix-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://cavelix.vercel.app
      - key: COMPILER_URL
        value: http://your-ec2-public-dns:8080/api
    healthCheckPath: /api/health
